name: flutter_example
description: Flutter Example project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.10

  state_notifier: ^0.7.0
  flutter_state_notifier: ^0.7.0
  provider: ^5.0.0

  json_serializable: ^5.0.2
  freezed_annotation: ^0.15.0

  cupertino_icons: ^1.0.2

  dio: ^4.0.1
  retrofit: ^2.0.1

  auto_route: ^3.0.4

  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  freezed: ^0.15.0
  retrofit_generator: ^2.0.0+1

  flutter_lints: ^1.0.0

  auto_route_generator: ^3.0.1

flutter:
  uses-material-design: true
