name: flutter_example
description: Flutter Example project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3

  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1
  provider: ^6.0.2

  json_serializable: ^6.1.5
  freezed_annotation: ^1.1.0

  dio: ^4.0.4
  retrofit: ^3.0.1+1

  auto_route: ^3.2.4

  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  freezed: ^1.1.1
  retrofit_generator: ^4.0.1

  flutter_lints: ^1.0.4

  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
